service: admin
runtime: nodejs8
default_expiration: "2m"

handlers:
- url: /((?:runtime|main|polyfills|styles|vendor|auth-auth-module)\.js|favicon\.ico)
  secure: always
  redirect_http_response_code: 301
  static_files: dist/\1
  upload: dist/.*

- url: /assets/(.*)
  secure: always
  redirect_http_response_code: 301
  static_files: dist/assets/\1
  upload: dist/assets/.*

- url: /.*
  secure: always
  redirect_http_response_code: 301
  static_files: dist/index.html
  upload: dist/index\.html
  http_headers:
    Strict-Transport-Security: max-age=31536000; includeSubDomains
    X-Frame-Options: ALLOWALL
